language: php
php:
  - '7.0'


services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - vendor

install:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.1' && $TRAVIS_PHP_VERSION != hhv* ]]; then
        # disable xdebug for performance reasons when code coverage is not needed. note: xdebug on hhvm is disabled by default
        phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # core framework:
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.3.1"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:

  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version

  # initialize databases
  - travis_retry mysql -e 'CREATE DATABASE `vps_tools_test`;';
  - mysql -e "CREATE USER 'travis'@'localhost' IDENTIFIED WITH mysql_native_password;";
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'localhost' WITH GRANT OPTION;";

  # enable code coverage on PHP 7.1, only one PHP version needs to generate coverage data
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
script:
  # ensure no files contain UTF-8 byte order mark
  - if ! grep -rlI $'\xEF\xBB\xBF' framework/ ; then echo "no utf8 BOM found"; else echo "found utf8 BOM in some files. See above."; exit 1; fi
  # validate composer.json
  - composer validate --no-check-lock
  - cd framework && composer validate --no-check-lock && cd ..
  # run PHPUnit
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS --exclude-group mssql,oci,wincache,xcache,zenddata,cubrid

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi