language: php
php:
  - '7.0'


services:
  - mysql

# cache vendor dirs
cache:
  directories:
    - vendor

install:
  - |
    if [[ $TRAVIS_PHP_VERSION != '7.1' && $TRAVIS_PHP_VERSION != hhv* ]]; then
        # disable xdebug for performance reasons when code coverage is not needed. note: xdebug on hhvm is disabled by default
        phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi
  - composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # core framework:
  - composer global require "fxp/composer-asset-plugin:^1.3.1"
  - composer install --prefer-dist --no-interaction

before_script:

  # show some versions and env information
  - php -r "echo INTL_ICU_VERSION . \"\n\";"
  - php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
  - mysql --version

  # initialize databases
  - mysql -e 'CREATE DATABASE `vps_tools_test`;';
  - mysql -e "CREATE USER 'vps_tools_test'@'localhost' IDENTIFIED BY '123';";
  - mysql -e "GRANT ALL ON vps_tools_test.* TO 'vps_tools_test'@'localhost';";

  # enable code coverage on PHP 7.1, only one PHP version needs to generate coverage data
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
script:
  # validate composer.json
  - composer validate --no-check-lock
  # run PHPUnit
  - phpunit --configuration tests/phpunit.xml

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '7.1' ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi